# Generated by Django 3.1.2 on 2021-04-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTerminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SW', models.TextField()),
                ('T1', models.IntegerField()),
                ('T2', models.IntegerField()),
                ('T3', models.IntegerField()),
                ('T4', models.IntegerField()),
                ('T5', models.IntegerField()),
                ('TS', models.IntegerField()),
            ],
            options={
                'db_table': 'data_terminal',
            },
        ),
    ]
