# Generated by Django 3.1.2 on 2021-04-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SW', models.TextField()),
                ('alert_type', models.TextField(default='Ping Lost')),
                ('alert_datetime', models.IntegerField()),
            ],
            options={
                'db_table': 'alert_report',
            },
        ),
        migrations.AddField(
            model_name='dataterminal',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
