# Generated by Django 3.1.2 on 2021-04-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210421_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertreport',
            name='email_alert_datetime',
            field=models.IntegerField(null=True),
        ),
    ]
