# Generated by Django 3.1.2 on 2021-04-23 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alertreport_email_alert_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertreport',
            name='data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.dataterminal'),
        ),
    ]
